# Generated by Django 3.2.9 on 2021-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211109_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitemmodel',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
